### ISSUE TITLE
MSVC: error C2039: 'value': is not a member of 'boost::proto'

### ISSUE THREAD

**Issue by matbech** [boostorg/proto#18]
MSVC 16.4.0 Preview 1 fails with this compile error:
boost\boost\proto\generate.hpp(239,20): error C2039: 'value': is not a member of 'boost::proto'

Affected line:
            proto::value(that.proto_expr_) = proto::value(e);

**Comment by matbech** [comment]
Ah, it seems this was already fixed with this commit in the develop branch:
https://github.com/boostorg/proto/pull/2/files

**Comment by k15tfu** [comment]
Hi @ericniebler ! I have the same issue in VC2019. Do you know why it wasn't included in 1.71?

**Comment by zhongwm** [comment]
I have the same issue in VC2019, yesterday updated VS2019 community to newest, compilation broken.

**Comment by UnknownObject000** [comment]
I have the same issue in VC1029 too,mine is Visual Studio 2019
