### ISSUE TITLE
MSVC: error C2039: 'value': is not a member of 'boost::proto'

### ISSUE THREAD

**Issue by zhongwm** [boostorg/proto#20]
https://github.com/boostorg/proto/issues/18
I am having the same issue in VC2019 community newest version.

**Comment by tobias-loew** [comment]
I've got the same error in boost/proto/generate.hpp(239)
The bug seems to be fixed in the "develop" branch, where line 233 is replaced by
` #if BOOST_WORKAROUND(BOOST_MSVC, < 1800)`

Please merge it over to master and put it release 1.72

**Comment by MarcelRaad** [comment]
There's even an open PR for that: https://github.com/boostorg/proto/pull/19

**Comment by tobias-loew** [comment]
I wrote a mail to the boost-developer list:
http://boost.2283326.n4.nabble.com/release-proto-MSVC-19-24-28314-VS-2019-16-4-0-won-t-compile-proto-s-generate-hpp-td4710720.html

**Comment by ericniebler** [comment]
The fix has been merged to master. Fingers crossed, all should be well again. Pls reopen if that's not the case.

**Comment by kanstantsin-chernik** [comment]
Any workarounds for current release?
